### ISSUE TITLE
TODO: pip, apt에서 새로운 패키지를 설치해야 하는 확장 지원

### ISSUE THREAD

**Issue by ghost** [thirdscam/SD-WebUI-Docker#1]
docker-compose.yml의 "PIP_PKGS"로 따로 분리해 패키지 설치하도록 Dockerfile 수정하기

```yml
version: '3.9'
services:
    ...
    environment:
      - CLI_ARGS=...
      - PIP_PKGS="ppap bbab ..." # In Dockerfile: pip install ppap bbab ...
    ...
```
